name: Deploy

on:
  workflow_dispatch:
  
permissions:
  contents: write  # Adiciona permissão de escrita para o conteúdo
  
jobs:
  deploy:
    uses: Brug-Org/action_automation/.github/workflows/rw_update-wiki.yml@main
    with:
      ambiente: 'dev'
      tag: 'release-2.36.5'

  # print-wiki-content:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Wiki
  #       run: |
  #         git clone https://github.com/${{ github.repository }}.wiki.git
  #         cd $(basename ${{ github.repository }}.wiki)
      
  #     - name: Print Wiki Page Content
  #       run: |
  #         cd $(basename ${{ github.repository }}.wiki)
  #         cat Home.md


