name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call reusable workflow
        uses: ./.github/workflows/update-wiki.yml
        with:
          ambiente: 'dev'
          tag: 'release-1.34.5'

  # print-wiki-content:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Wiki
  #       run: |
  #         git clone https://github.com/${{ github.repository }}.wiki.git
  #         cd $(basename ${{ github.repository }}.wiki)
      
  #     - name: Print Wiki Page Content
  #       run: |
  #         cd $(basename ${{ github.repository }}.wiki)
  #         cat Home.md


