name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: owner/repo/.github/workflows/reusable-workflow.yml@branch
    with:
      prefix: 'TI'
