name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: Brug-Org/action_automation/.github/workflows/reusable-workflow.yml@main
    with:
      prefix: 'TI'
