name: Main Workflow

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  deploy:
    uses: Brug-Org/action_automation/.github/workflows/reusable-workflow.yml@main
    with:
      prefix: 'ti'
