name: Reusable Workflow

on:
  workflow_call:
    inputs:
      prefix:
        required: true
        type: string

jobs:
  list-validate-create-matrix:
    name: ""
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Listar Environments
        id: list-envs
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/environments > environments.json
          cat environments.json

      - name: Validar Environments
        id: validate-envs
        run: |
          prefix=${{ inputs.prefix }}
          valid_envs=$(jq -r '.environments[].name' environments.json | grep "^$prefix")
          echo "Environments válidos: $valid_envs"
          echo "valid_envs=$valid_envs" >> $GITHUB_ENV

      # - name: Validar variáveis de ambiente
      #   id: validate-env
      #   run: |
      #     for var in $(printenv); do
      #       if [[ $var == ${{ inputs.prefix }}* ]]; then
      #         echo "Variável válida: $var"
      #       else
      #         echo "Variável inválida: $var"
      #       fi
      #     done

      - name: Criar matrix
        id: set-matrix
        run: |
          matrix=$(echo "${{ steps.validate-envs.outputs.valid_envs }}" | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

      # - name: Criar matrix
      #   id: set-matrix
      #   run: |
      #     matrix=$(printenv | grep '^${{ inputs.prefix }}' | cut -d= -f1 | jq -R -s -c 'split("\n")[:-1]')
      #     echo "::set-output name=matrix::$matrix"

  run-matrix-jobs:
    needs: list-validate-create-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_name: ${{ fromJson(needs.list-validate-create-matrix.outputs.matrix) }}
    steps:
      - name: Usar Environment
        run: echo "Usando o Environment ${{ matrix.env_name }}"
    environment:
      name: ${{ matrix.env_name }}
