name: Reusable Workflow

on:
  workflow_call:
    inputs:
      prefix:
        required: true
        type: string

jobs:
  list-validate-create-matrix:
    name: ""
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Listar Environments
        id: list-envs
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/environments > environments.json
          cat environments.json

      - name: Validar Environments
        id: validate-envs
        run: |
          prefix=${{ inputs.prefix }}
          valid_envs=$(jq -r '.environments[].name' environments.json | grep "^$prefix")
          echo "valid_envs=$valid_envs" >> $GITHUB_ENV

      - name: Criar matrix
        id: set-matrix
        run: |
          matrix=$(echo "${{ env.valid_envs }}" | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  run-matrix-jobs:
    needs: list-validate-create-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env_name: ${{ fromJson(needs.list-validate-create-matrix.outputs.matrix) }}
    steps:
      - name: Usar Environment
        run: echo "Usando o Environment ${{ matrix.env_name }}"
    environment:
      name: ${{ matrix.env_name }}
